name: Run tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.17.1

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Build
        run: |
          pnpm install
          NODE_ENV=production pnpm build

      - name: Test
        run: |
          pnpm lint
          pnpm test
