name: Run tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm ci
          NODE_ENV=production npm run build

      - name: Test
        run: |
          npm run lint
          npm test
